# Generated by Django 5.1 on 2024-09-11 15:55

import module_SiteSettings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='site_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Welcome, Please edit Site_settings at admin_page', max_length=50, verbose_name='عنوان / نام فروشگاه')),
                ('address', models.TextField(default='mehdi.kr@gmail.com', max_length=1000, verbose_name='آدرس پستی')),
                ('about_us', models.TextField(default='mehdi.kr@gmail.com', verbose_name='درباره فروشگاه')),
                ('phone', models.CharField(default='+989356818853', max_length=15, verbose_name='شماره تماس')),
                ('pre_phone', models.CharField(default='021', max_length=4, verbose_name='پیش شماره (مثال : ۰۲۱)')),
                ('fax', models.CharField(default='0', max_length=15, verbose_name='فکس')),
                ('email', models.EmailField(default='mehdi.kr@gmail.com', max_length=254, verbose_name='ایمیل')),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to=module_SiteSettings.models.upload_image_path, verbose_name='لوگوی فروشگاه')),
                ('index_banner1', models.ImageField(blank=True, default=None, null=True, upload_to=module_SiteSettings.models.upload_image_path_banner1, verbose_name='بنر شماره ۱ (428*856)')),
                ('index_banner1_link', models.CharField(default='/', max_length=250, verbose_name='لینک بنر شماره ۱')),
                ('index_banner2', models.ImageField(blank=True, default=None, null=True, upload_to=module_SiteSettings.models.upload_image_path_banner2, verbose_name='بنر شماره ۲ (428*856)')),
                ('index_banner2_link', models.CharField(default='/', max_length=250, verbose_name='لینک بنر شماره ۲')),
                ('favicon', models.ImageField(default='images/favicon.ico', upload_to=module_SiteSettings.models.upload_image_path_favicon, verbose_name='آیکون وبسایت (ico.)')),
                ('transport_limit', models.BooleanField(default=False, verbose_name='امکان ارسال رایگان')),
                ('transport_limit_price', models.CharField(default=500000, max_length=15, verbose_name='حداقل مبلغ خرید برای ارسال رایگان')),
                ('transport_price', models.CharField(default=50000, max_length=15, verbose_name='هزینه حمل و نقل مرسوله')),
                ('is_repairing', models.BooleanField(default=False, verbose_name='حالت تعمیر')),
                ('active', models.BooleanField(default=False, unique=True, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'ثبت/ویرایش تنظیمات',
                'verbose_name_plural': 'مدیریت تنظیمات وبسایت',
            },
        ),
    ]
