# Generated by Django 5.1 on 2024-09-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsForm_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('msg', models.TextField(verbose_name='متن پیام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('seen', models.BooleanField(default=False, verbose_name='خوانده شده/نشده')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ درج نظر')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام های کاربران',
            },
        ),
    ]
