# Generated by Django 5.1 on 2024-09-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر اسلایدر (۸۹۰ * ۱۷۸۰)')),
                ('url_link', models.CharField(max_length=250, verbose_name='آدرس لینک')),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدر',
            },
        ),
    ]
