# Generated by Django 5.1 on 2024-09-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان برچسب')),
                ('slug', models.CharField(blank=True, max_length=50, verbose_name='عنوان آدرس')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('products', models.ManyToManyField(blank=True, to='module_products.product', verbose_name='محصولات مرتبط به این تگ')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
    ]
