# Generated by Django 5.1 on 2024-09-11 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Main_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت (شده / نشده)')),
                ('payment_date', models.DateTimeField(null=True, verbose_name='تاریخ پرداخت')),
                ('payment_status', models.IntegerField(default=2, verbose_name='وضعیت پرداخت (۰=موفق ۱=ناموفق ۲=بررسی ۳=لغو شده ۴=مرجوع شده)')),
                ('package_status', models.IntegerField(default=1, verbose_name='وضعیت بسته (۰=جمع آوری ۱=پک شده ۲=ارسال\u200cشده. مرجوعی: ۰=بررسی ۱=استرداد\u200cمبلغ ۲=غیر قابل قبول)')),
                ('transport_price', models.CharField(default=0, max_length=6, verbose_name='هزینه حمل و نقل')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پرداخت')),
                ('post_tracking', models.CharField(blank=True, max_length=150, null=True, verbose_name='کد رهگیری مرسوله')),
                ('order_status', models.CharField(blank=True, max_length=150, null=True, verbose_name='کد پیگیری سفارش')),
                ('error_message', models.CharField(blank=True, max_length=250, null=True, verbose_name='پیام درگاه پرداخت')),
                ('cart_notes', models.TextField(blank=True, null=True, verbose_name='توضیحات سفارش')),
                ('receiver_first_name', models.CharField(default='', max_length=120, verbose_name='نام گیرنده')),
                ('receiver_last_name', models.CharField(default='', max_length=120, verbose_name='نام خانوادگی گیرنده')),
                ('receiver_address', models.TextField(default='', verbose_name='آدرس گیرنده')),
                ('receiver_phone', models.CharField(default=0, max_length=12, verbose_name='تلفن گیرنده')),
                ('receiver_email', models.CharField(default=0, max_length=50, verbose_name='ایمیل گیرنده')),
                ('receiver_postalcode', models.CharField(default=0, max_length=12, verbose_name='کد پستی')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='آیدی مالک سبد خرید')),
            ],
            options={
                'verbose_name': 'سبد خرید کاربر',
                'verbose_name_plural': 'سبد های خرید کاربران',
            },
        ),
        migrations.CreateModel(
            name='Order_Detail_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_products.product', verbose_name='محصول')),
                ('from_Main_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_orders.order_main_model', verbose_name='سبد خرید مربوطه')),
            ],
            options={
                'verbose_name': 'محتوای سبد خرید',
                'verbose_name_plural': 'محصولات داخل سبد خرید ها',
            },
        ),
    ]
