# Generated by Django 5.1 on 2024-09-11 15:55

import django.db.models.deletion
import module_categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.CharField(max_length=100, verbose_name='عنوان در URL')),
                ('banner', models.ImageField(blank=True, null=True, upload_to=module_categories.models.upload_image_path, verbose_name='بنر دسته بندی برای اسلایدر و غیره (اختیاری)')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product_SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.CharField(max_length=100, verbose_name='عنوان در URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_categories.productcategories', verbose_name='دسته بندی اصلی')),
            ],
            options={
                'verbose_name': 'زیر دسته',
                'verbose_name_plural': 'زیر دسته بندی ها',
            },
        ),
    ]
