# Generated by Django 5.1 on 2024-09-11 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='موبایل')),
                ('mellicode', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='تایید موبایل')),
                ('Email_verified', models.BooleanField(default=False, verbose_name='تایید ایمیل')),
                ('last_ip', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='آخرین آدرس آیپی')),
                ('birth_jalali', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ تولد')),
                ('new_phone_to_change', models.CharField(blank=True, max_length=11, null=True, verbose_name='موبایل جدید برای تغییر')),
                ('phone_verify_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد تایید ارسال شده به موبایل')),
                ('phone_verify_hash_code', models.CharField(blank=True, max_length=256, null=True, verbose_name='کد تایید هش موبایل')),
                ('phone_verify_date_code', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال کد تایید به موبایل')),
                ('email_verify_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='کد تایید ارسال شده به ایمیل')),
                ('email_verify_hash_code', models.CharField(blank=True, max_length=256, null=True, verbose_name='کد تایید هش ایمیل')),
                ('email_verify_date_code', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال کد تایید به ایمیل')),
                ('IsSeller', models.BooleanField(default=False, verbose_name='فروشنده')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه')),
            ],
            options={
                'verbose_name': 'سایر مشخصات کاربر',
                'verbose_name_plural': 'سایر مشخصات کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='نام')),
                ('family', models.CharField(blank=True, max_length=250, null=True, verbose_name='نام خانوادگی')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='شهر')),
                ('address_detail', models.CharField(blank=True, max_length=250, null=True, verbose_name='آدرس پستی')),
                ('post_code', models.CharField(blank=True, max_length=250, null=True, verbose_name='کد پستی')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='موبایل')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='ایمیل')),
                ('phone_verify_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='کد تایید ارسال شده به موبایل')),
                ('phone_verify_date_code', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال کد تایید به موبایل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه')),
            ],
            options={
                'verbose_name': 'آدرس کاربر',
                'verbose_name_plural': 'آدرس کاربران',
            },
        ),
        migrations.CreateModel(
            name='WishlistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه')),
            ],
        ),
    ]
