# Generated by Django 5.1 on 2024-09-11 15:55

import django.db.models.deletion
import module_products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='زمان اضافه شدن محصول به وبسایت')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت (تومان)')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('main_big_image', models.ImageField(null=True, upload_to=module_products.models.upload_image_path, verbose_name='تصویر اصلی محصول (سایز بزرگ)')),
                ('main_small_image', models.ImageField(null=True, upload_to=module_products.models.upload_image_path, verbose_name='تصویر اصلی محصول(سایز کوچک ۱۸۵*۱۸۵)')),
                ('active', models.BooleanField(verbose_name='فعال/غیرفعال')),
                ('stock', models.IntegerField(verbose_name='موجودی')),
                ('visit_counter', models.IntegerField(default=0, verbose_name='تعداد بازدید محصول')),
                ('IncomingPrice', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True, verbose_name='قیمت خرید فروشنده(تومان)')),
                ('AutoPriceUpdate', models.BooleanField(default=False, verbose_name='تایین قیمت خودکار')),
                ('PricePercent', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='ضریب افزایش قیمت')),
                ('Seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Seller', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده محصول')),
                ('categories', models.ManyToManyField(blank=True, to='module_categories.productcategories', verbose_name='دسته بندی های اصلی')),
                ('sub_categories', models.ManyToManyField(blank=True, to='module_categories.product_subcategories', verbose_name='دسته بندی های فرعی')),
                ('wisher_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='موجود در لیست علاقه مندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Products_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_image', models.ImageField(upload_to=module_products.models.upload_image_gallery, verbose_name='تصویر بزرگ')),
                ('small_image', models.ImageField(upload_to=module_products.models.upload_image_gallery, verbose_name='تصویر کوچک ۱۸۵*۱۸۵')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_products.product', verbose_name='محصول مربوطه')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
    ]
