# Generated by Django 5.1 on 2024-10-14 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products_Gallery',
            new_name='ProductsGallery',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='AutoPriceUpdate',
            new_name='auto_price_update',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='IncomingPrice',
            new_name='incoming_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PricePercent',
            new_name='price_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Seller',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_seller', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده محصول'),
        ),
    ]
